-- Enigma-NG Todo Database Seed
-- Run this at session start via the sql tool (INSERT OR IGNORE = idempotent).

INSERT OR IGNORE INTO todos (id, title, status) VALUES
-- Open Workstreams
('extension-mechanical-usage',        'Extension interconnect architecture review',    'in_progress'),
('coupon-testing-review',             'Board-level coupon & PAS test coverage',        'pending'),
('battery-connector-final-review',    'Battery connector final review',                'blocked'),
('general-pin-mapping-schematic-capture', 'General pin mapping / schematic capture',  'done'),
('rerun-deep-reviews',                'Final pre-V1 deep review cycle',               'pending'),
-- Electronics Deferrals
('ctlh1-deferred',                    'Controller CTL-H1 deferred finding',           'done'),
('rotor-power-analysis-ministack',    'Recalculate Rotor Board_Layout power analysis for mini-stack', 'done'),
('rotor-esd-tvs',                     'Rotor ESD TVS (PRTR5V0U10AZ) sourcing',       'done'),
('rotor-variant-refdes-schematic',    'Rotor variant U3/U4 KiCAD DNF approach',       'done'),
('rotor-refdes-reallocate',           'Rotor RefDes gap removal: R2-R7 -> R1-R6',    'done'),
('production-folder',                 'Create design/Production/ folder with JLCPCB constraints doc',  'done'),
('grs-production-link',               'Update GRS to reference design/Production/ folder',             'done'),
('display-addon-board',               'Display add-on board (v2.0)',                  'blocked'),
('cpld-production-replacement',       'CPLD production replacement review (v2.0)',    'blocked'),
('connector-thermal-verification',    'Connector thermal/current derating',           'done'),
('full-pn-review',                    'Full supplier PN sweep pre-schematic',         'pending'),
('post-merge-final-design-bom-sweep', 'Post-merge final design/BOM consolidation sweep', 'pending'),
('footprint-requests-pending',        'Outstanding footprint requests / downloads',   'pending'),
('bom-func-notes-sweep',              'BOM function notes conformity sweep',          'done'),
('m25-m3-dec-exception',              'M2.5 mounting hole DEC exception for daughterboards', 'done'),
-- Mechanical Deferrals
('rotor-shaft-diameter',              'Rotor PCB shaft hole diameter',                'pending'),
('rotor-rolling-element',             'Rotor rolling element diameter spec',          'pending'),
('rotor-alloy-grade',                 'Rotor disc alloy grade selection',             'pending'),
('rotor-shaft-mechanism',             'Rotor shaft retention mechanism',              'pending'),
('display-aperture',                  'Main enclosure display aperture (v2.0)',       'blocked'),
('system-assembly-harnesses',         'System Assembly harness definitions',          'pending'),
('system-assembly-connectors',        'System Assembly connector list',               'pending'),
-- Software Deferrals
('ltc3350-telemetry',                 'LTC3350 I2C telemetry Linux driver',           'pending'),
('cpld-timing-load',                  'CPLD timing & load characterisation',          'pending'),
-- Standards & Certification
('da-01',                             'DA-01: Coupon ESD protection requirement',     'done'),
('da-02',                             'DA-02: Classroom deployment ESD policy',       'done'),
('naming-convention-sweep',           'Naming consistency sweep: PM dock / Stator dock', 'done'),
('da-04',                             'DA-04: Consolidated BOM PM component update',  'done'),
('compliance-testing',                'Environmental and EMC compliance testing',     'pending'),
('emc-testing',                       'EMC testing',                                   'pending'),
('environmental-testing',             'Environmental testing',                         'pending'),
('security-testing',                  'Security testing',                              'pending'),
('bom-pre-prototype-check',           'BOM verification gate 1 (pre-prototype)',      'pending'),
('bom-pre-production-check',          'BOM verification gate 2 (pre-production)',     'pending'),
-- Pass 6 Deferred Items
('jdb-board-rename',                  'JDB board rename to JTAG Module',              'done'),
('bypass-cap-audit-100nf',            '100nF bypass cap DigiKey PN audit',            'done'),
('reset-n-prefix-decision',           'RESET_N net name prefix decision',             'done'),
('connector-stacking-height-review',  'ERF8/ERM8 stacking height review',             'done'),
('plugboard-assembly-spec',           'Plugboard Assembly specification',              'done'),
('enc-connector-review-pre-pcb',      'ENC connector review pre-PCB manufacturing',   'done'),
('bom-system-qty-audit',              'Consolidated BOM system quantity audit',        'done'),
('mh-refdes-standardise',             'Mounting hole RefDes standardisation',         'done'),
('jdb-standoff-height',               'JDB standoff height and DF40 BtB connector',   'done'),
('jdb-fr-renumber',                   'JDB FR renumbering after FR-02/03 collapse',   'done'),
('jdb-ft232h-3v3-vregin',             'FT232H Rev C 3V3 VREGIN (v2.0)',              'blocked'),
('ctl-t1-wurth-datasheet-review',     'Wurth 750318938 datasheet review',             'done'),
('ctl-t1-transformer-decision',       'CTL T1 transformer selection decision',        'done'),
-- Project Milestones
('review-mounting-holes',             'Mounting hole verification per board',         'done'),
('interim-electronics-review-1',      'Review gate 1: pass 3 fixes verified',        'pending'),
('interim-electronics-review-2',      'Review gate 2: post-coupon review',           'pending'),
('interim-electronics-review-3',      'Review gate 3: post-schematic / pre-prototype', 'pending'),
('interim-electronics-review-4',      'Review gate 4: pre-production run',           'pending'),
('prototype-pcb-manufacturing',       'Prototype PCB manufacturing (JLCPCB)',        'pending'),
('prototype-system-complete',         'Prototype system verification complete',       'pending'),
('release-candidate-production',      'Release candidate production manufacturing',  'pending'),
('version-one-complete',              'Version 1.0 complete',                        'pending'),
('review-pass-7',                     'Design review pass 7',                        'done'),
('review-pass-8',                     'Design review pass 8',                        'done'),
('review-pass-9',                     'Design review pass 9',                        'done'),
('review-pass-10',                    'Design review pass 10',                       'done'),
('download-missing-3d-models',        'Download remaining 3D models for library parts', 'done'),
('review-pass-11',                    'Design review pass 11',                       'pending'),
('review-pass-12',                    'Design review pass 12',                       'pending'),
-- review-clean-passes-gate: MUST add new review-pass-x dep to deps.sql whenever a new pass is created
('review-clean-passes-gate',          'Gate: two consecutive clean review passes achieved', 'pending'),
-- Documentation improvements
('ascii-to-mermaid-diagrams',         'Replace ASCII flow/block diagrams with Mermaid fenced blocks', 'done'),
-- Mermaid Diagrams
('board-interconnect-diagram',        'block-beta board interconnect diagram in Boards_Overview.md',            'done'),
('system-config-variants-diagrams',   'flowchart TD system config variants in System_Architecture.md',          'pending'),
('version-1-documentation',           'Version 1.0 documentation package',                                      'pending'),
('ctl-component-diagram',             'flowchart TD CTL circuit component diagram in Controller/Design_Spec.md',   'done'),
('pm-component-diagram',              'flowchart TD PM circuit component diagram in Power_Module/Design_Spec.md',  'done'),
('sta-component-diagram',             'flowchart TD STA circuit component diagram in Stator/Design_Spec.md',      'done'),
('rotor-component-diagram',           'flowchart TD Rotor circuit component diagram in Rotor/Design_Spec.md',     'done'),
('ext-component-diagram',             'flowchart TD EXT circuit component diagram in Extension/Design_Spec.md',   'done'),
('ref-component-diagram',             'flowchart TD REF circuit component diagram in Reflector/Design_Spec.md',   'done'),
('enc-component-diagram',             'flowchart TD ENC circuit component diagram in Encoder/Design_Spec.md',     'done'),
('jm-component-diagram',              'flowchart TD JM circuit component diagram in JTAG_Module/Design_Spec.md',  'done'),
('usm-component-diagram',             'flowchart TD USM circuit component diagram in User_Settings_Module/Design_Spec.md', 'done'),
('am-component-diagram',              'flowchart TD AM circuit component diagram in Actuation_Module/Design_Spec.md',      'done'),
-- Review Pass 8 todos
('stackup-impedance-recalc',                  'Select optimal JLCPCB stackup based on impedance-controlled trace width manufacturability', 'done'),
('bulk-caps-per-power-source-or-conversion',  'Bulk decoupling at every power source and conversion point',                                'done'),
('ctl-l02-refdes-gap',                        'Fix Controller board RefDes numbering gap',                                                 'done'),
('enc-cpld-spare-pins-rule',                  'Add CPLD spare-pins rule to review agent-directives',                                       'done'),
('jtag-pin1-silkscreen-grs',                  'Add pin-1 silkscreen marker requirement to GRS',                                            'done'),
('jtag-integrity-resistor-value-reconcile',   'Reconcile JTAG termination resistor values across all boards',                              'done'),
('mcp23017-gpb7-silicon-fixed-review',        'Review and fix MCP23017 GPB7 silicon-fixed output-only pin issue',                         'done'),
('rot-i2c-residual-removal',                  'Remove residual I2C references from Rotor design',                                          'done'),
('consolidate-design-spec-content',           'Consolidate and normalise all Design Spec content',                                         'pending'),
('usm-spdt-switch-floating-review',           'Review USM SPDT switch floating pin concern',                                               'done'),
('am-button-review-production',               'Review Actuation Module buttons for production version',                                     'done'),
-- T1 transformer analysis todos
('ctl-t1-bourns-component-analysis',          'Analyse supporting component changes for Bourns POE060-FD20120S T1 replacement',             'done'),
('ctl-t1-coilcraft-v2-review',                'v2: Review Coilcraft POE600F-12L production readiness',                                     'blocked'),
('tps25751-i2c-review',                       'Review TPS25751 I2C connectivity for runtime PDO configuration',                            'done'),
('rename-sys-reset-n',                        'Rename SYS_RESET_N signal to CPLD_RESET_N across all design files',                         'done'),
('data-plate-standardisation',                'Standardise Data Plate entries across all board Design_Spec.md files',                       'done'),
('design-log-restructure',                    'Restructure Design Log into per-DEC files with index',                                       'done'),
('copilot-dir-restructure',                   'Restructure .copilot/ directory for context efficiency',                                     'done'),
('ctl-t1-tdk-a120-component-analysis',        'Analyse supporting component changes for TDK B82806D0060A120 T1 option (12V)',               'done'),
('ctl-t1-tdk-library-import',                 'Import TDK B82806D footprint zip and add 3D model to legacy library',                       'done'),
('ctl-t1-tdk-topology-confirm',               'Contact TDK apps engineering — B82806D0060A120 topology confirmation',                      'done'),
-- Stackup consolidation sweep
('grs-stackup-section',                       'Add GRS §2.3 PCB Stackup Definitions',                                                      'done'),
('design-log-dec066',                         'Append DEC-066 to Design_Log.md',                                                           'done'),
('jlcpcb-mfg-cross-refs',                     'Update JLCPCB_Manufacturing.md §1.1 and §1.2 cross-refs',                                   'done'),
('am-stackup-simplify',                       'Simplify AM DR-AM-01, DR-AM-09, remove blockquote',                                         'done'),
('ctl-stackup-simplify',                      'Simplify CTL §9.2 — remove physical table, add GRS ref',                                    'done'),
('enc-stackup-simplify',                      'Simplify ENC §9; add GRS §2.3.1 reference',                                                 'done'),
('ext-stackup-simplify',                      'Simplify EXT §4 + fix DR-EXT-01 stale code',                                                'done'),
('jm-stackup-simplify',                       'Simplify JM §5 + fix DR-JM-01 stale code',                                                 'done'),
('pm-stackup-simplify',                       'Update PM DR-PM-13 and §1; add GRS §2.3.3 reference',                                       'done'),
('ref-stackup-simplify',                      'Simplify REF §6; add GRS §2.3.1 reference',                                                 'done'),
('rot-stackup-simplify',                      'Simplify ROT §4; add GRS §2.3.1 reference',                                                 'done'),
('sta-stackup-simplify',                      'Simplify STA §7; add GRS §2.3.1 reference',                                                 'done'),
('usm-stackup-simplify',                      'Simplify USM §8; add GRS §2.3.1 reference',                                                 'done'),
-- Design discussion merge todos
('design-discussion-merge',          'Merge design discussions into main design',                         'in_progress'),
('merge-grs-6layer-stackup',         'Add 6-layer board stackup section to GRS',                         'done'),
('merge-create-cypher-board',        'Create and refine Cypher Board Design_Spec and Board_Layout',       'done'),
('merge-cypher-board-j3j6-pinouts',  'Define full 50-pin allocation for Cypher Board J3-J6 connectors',  'pending'),
('merge-ctl-dock-usb-allocation',    'Define USB D+/D- pin allocation in Cypher Board J1 CTL dock',      'pending'),
('merge-create-stack-input',         'Create Stack-Input Board Design',                                  'done'),
('merge-update-ctl-board',           'Update CTL Board Design — remove JM and AM sub-systems',           'pending'),
('merge-create-stack-output',        'Create Stack-Output Board Design',                                  'done'),
('merge-create-stack-blanking',      'Create Stack-Blanking Panel Board Design',                         'done'),
('merge-create-stack-interposer',   'Create Stack-Interposer Board Design',                             'done'),
('merge-create-cypher-input',        'Create Cypher-Input Board Design',                                 'done'),
('merge-create-cypher-output',       'Create Cypher-Output Board Design',                                'pending'),
('merge-create-plugboard',           'Create Plugboard Board Design',                                    'pending'),
('merge-update-top-level-docs',      'Update Boards_Overview, System_Architecture and related docs',     'pending'),
('merge-remove-old-boards',          'Move retiring board design files to .recycle-bin/',                'pending'),
('merge-consistency-review',         'Review all merged design files for consistency',                   'pending'),
('merge-missing-components',         'Identify and select missing/supporting BOM components',            'pending'),
('merge-final-review',               'Final full review of design merge and completion sign-off',        'pending'),
('todo-clean-up-requirement-details', 'Cleaning up FR/DR requirement detail across design files',         'pending'),
('merge-diagrams-review',            'Review and update draw.io diagrams for Cypher system merge',       'pending'),
('cypher-input-led-independent-rgb-pwm-review', 'Review LED colour controls for independent per-channel RGB PWM', 'pending'),
('usm-cfg-refmap-removal-review', 'Revisit USM Bank 2/CFG_REFMAP removal before next full design review', 'pending');
